version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    commit-message:
      prefix: "GH Actions"

  # Keep Docusaurus packages aligned
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    allow:
      - dependency-name: "@docusaurus/*"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
    commit-message:
      prefix: "chore(deps)"
